### ISSUE TITLE
LookupError: No installed app with label 'netbox_inventory'.

### ISSUE THREAD

**Issue by ismailkalolwala** [ArnesSI/netbox-inventory#133]
root@dc-netbox-srv01:/opt/netbox_inventory/netbox-inventory-master# python3 manage.py migrate
python3: can't open file '/opt/netbox_inventory/netbox-inventory-master/manage.py': [Errno 2] No such file or directory
root@dc-netbox-srv01:/opt/netbox_inventory/netbox-inventory-master# source /opt/netbox/venv/bin/activate
(venv) root@dc-netbox-srv01:/opt/netbox_inventory/netbox-inventory-master# cd /opt/netbox/netbox/
(venv) root@dc-netbox-srv01:/opt/netbox/netbox# cd /opt/netbox/netbox/
(venv) root@dc-netbox-srv01:/opt/netbox/netbox# python3 manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/apps/registry.py", line 158, in get_app_config
    return self.app_configs[app_label]
KeyError: 'netbox_inventory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 8, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 26, in <module>
    app = apps.get_app_config(plugin_name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/apps/registry.py", line 165, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'netbox_inventory'.

exit
bash: $: command not found
bash: command substitution: line 3: syntax error near unexpected token `$'
bash: command substitution: line 3: `(venv) $ pip install netbox-inventory'
bash: VERSION: command not found
(venv) root@dc-netbox-srv01:/opt/netbox_inventory/netbox-inventory-master# cat /opt/netbox/netbox/netbox/settings.py | grep -i VERSION
VERSION = '3.5.8'

if sys.version_info < (3, 8):
        f"NetBox requires Python 3.8 or later. (Currently installed: Python {platform.python_version()})"
        release=VERSION,
    'version': VERSION,
    'python_version': sys.version.split()[0],
REST_FRAMEWORK_VERSION = '.'.join(VERSION.split('-')[0].split('.')[:2])  # Use major.minor as API version
    'ALLOWED_VERSIONS': [REST_FRAMEWORK_VERSION],
    'DEFAULT_VERSION': REST_FRAMEWORK_VERSION,
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
    'VERSION': VERSION,
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)

Please assist :  Kalolwalaismail@gmail.com

**Comment by matejv** [comment]
Please use [code formatting]/https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) when pasting console outputs. It makes it much easier to read and assist.

Anyhow, I can see you are running netbox version 3.5.8 and I suspect you installed the latest version of netbox_inventory - that is currently 1.5.1. Unfortunately this combination of versions is [not compatible](https://github.com/ArnesSI/netbox-inventory#compatibility). 

For netbox v3.5.8 the latest version of netbox-inventory is 1.4.4. You can install it with:

```
pip install netbox-inventory==1.4.4
```
